// SPDX-License-Identifier: GPL-3.0-only
//
// The EC-SRP5 implementation in this file is a port of elliptic_curves.py and
// encryption.py from petrunetworking/MAC-Telnet-Routeros (GPL-3.0), which is
// where the curve parameters, lift_x, redp1, the password validator and the
// confirmation derivation come from. The test vectors in ecsrp_test.go were
// generated by running that implementation.

package mt

import (
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"math/big"
)

// EC-SRP5 over Curve25519 in short Weierstrass form -- the login RouterOS 6.43
// and later actually accept. The legacy MD5 challenge is dead on those versions:
// the device stores only an SRP verifier, so MD5(0x00 || password || salt) can
// never be verified and every legacy login fails by construction.
//
// This needs only math/big and SHA-256. The session that follows is NOT
// encrypted, so there is no AES or HMAC anywhere in a MAC-Telnet client.

var (
	// p = 2^255 - 19
	curveP, _ = new(big.Int).SetString("7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed", 16)
	// r = group order
	curveR, _ = new(big.Int).SetString("1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed", 16)
	// short Weierstrass a and b, for y^2 = x^3 + ax + b
	curveA, _ = new(big.Int).SetString("2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa984914a144", 16)
	curveB, _ = new(big.Int).SetString("7b425ed097b425ed097b425ed097b425ed097b425ed097b4260b5e9c7710c864", 16)

	montA = big.NewInt(486662)

	big1 = big.NewInt(1)
	big2 = big.NewInt(2)
	big3 = big.NewInt(3)
)

// point is an affine point; inf marks the point at infinity.
type point struct {
	x, y *big.Int
	inf  bool
}

func fmod(x *big.Int) *big.Int { return new(big.Int).Mod(x, curveP) }

func finv(x *big.Int) *big.Int {
	return new(big.Int).ModInverse(fmod(x), curveP)
}

// sqrtModP returns both square roots of a, or nil if a is not a residue.
// p is 5 mod 8, so the Ed25519 shortcut applies and no Tonelli-Shanks is needed.
func sqrtModP(a *big.Int) (*big.Int, *big.Int) {
	a = fmod(a)
	if a.Sign() == 0 {
		return big.NewInt(0), big.NewInt(0)
	}
	// candidate = a^((p+3)/8)
	e := new(big.Int).Add(curveP, big3)
	e.Rsh(e, 3)
	c := new(big.Int).Exp(a, e, curveP)

	if new(big.Int).Mod(new(big.Int).Mul(c, c), curveP).Cmp(a) != 0 {
		// multiply by sqrt(-1) = 2^((p-1)/4)
		e2 := new(big.Int).Sub(curveP, big1)
		e2.Rsh(e2, 2)
		i := new(big.Int).Exp(big2, e2, curveP)
		c = fmod(new(big.Int).Mul(c, i))
		if new(big.Int).Mod(new(big.Int).Mul(c, c), curveP).Cmp(a) != 0 {
			return nil, nil
		}
	}
	return c, fmod(new(big.Int).Sub(curveP, c))
}

func addPoints(p1, p2 point) point {
	if p1.inf {
		return p2
	}
	if p2.inf {
		return p1
	}
	var num, den *big.Int
	if p1.x.Cmp(p2.x) == 0 {
		if fmod(new(big.Int).Add(p1.y, p2.y)).Sign() == 0 {
			return point{inf: true}
		}
		// lambda = (3x^2 + a) / 2y
		num = fmod(new(big.Int).Add(new(big.Int).Mul(big3, new(big.Int).Mul(p1.x, p1.x)), curveA))
		den = finv(new(big.Int).Mul(big2, p1.y))
	} else {
		num = fmod(new(big.Int).Sub(p2.y, p1.y))
		den = finv(new(big.Int).Sub(p2.x, p1.x))
	}
	lam := fmod(new(big.Int).Mul(num, den))
	x3 := fmod(new(big.Int).Sub(new(big.Int).Sub(new(big.Int).Mul(lam, lam), p1.x), p2.x))
	y3 := fmod(new(big.Int).Sub(new(big.Int).Mul(lam, new(big.Int).Sub(p1.x, x3)), p1.y))
	return point{x: x3, y: y3}
}

func scalarMult(k *big.Int, p point) point {
	res := point{inf: true}
	add := p
	for i := 0; i < k.BitLen(); i++ {
		if k.Bit(i) == 1 {
			res = addPoints(res, add)
		}
		add = addPoints(add, add)
	}
	return res
}

// liftX maps a Montgomery x to a Weierstrass affine point with the requested y
// parity. Returns ok=false when x is not on the curve.
func liftX(x *big.Int, parity int) (point, bool) {
	x = fmod(x)
	// y^2 = x^3 + A x^2 + x, on the Montgomery curve
	x2 := new(big.Int).Mul(x, x)
	y2 := new(big.Int).Add(new(big.Int).Mul(x2, x), new(big.Int).Mul(montA, x2))
	y2 = fmod(new(big.Int).Add(y2, x))

	// Weierstrass x is the Montgomery x shifted by A/3
	wx := fmod(new(big.Int).Add(x, new(big.Int).Mul(montA, finv(big3))))

	r1, r2 := sqrtModP(y2)
	if r1 == nil {
		return point{}, false
	}
	for _, y := range []*big.Int{r1, r2} {
		if int(y.Bit(0)) == parity {
			return point{x: wx, y: y}, true
		}
	}
	return point{x: wx, y: r1}, true
}

// toMontgomery converts back, returning the 32-byte big-endian Montgomery x and
// the y parity.
func toMontgomery(p point) ([]byte, int) {
	conv := fmod(new(big.Int).Sub(curveP, new(big.Int).Mul(montA, finv(big3))))
	x := fmod(new(big.Int).Add(p.x, conv))
	return leftPad(x.Bytes(), 32), int(p.y.Bit(0))
}

// basePoint is lift_x(9, even) -- note EVEN y, so it is the negation of the
// usual Curve25519 generator. Matching this exactly matters.
func basePoint() point {
	p, _ := liftX(big.NewInt(9), 0)
	return p
}

// PublicKey returns priv*G as a Montgomery x plus its y parity.
func PublicKey(priv []byte) ([]byte, int) {
	return toMontgomery(scalarMult(new(big.Int).SetBytes(priv), basePoint()))
}

// redp1 hashes until the value lands on the curve: MikroTik's hash-to-point.
func redp1(data []byte, parity int) point {
	x := sha256.Sum256(data)
	for {
		x2 := sha256.Sum256(x[:])
		if p, ok := liftX(new(big.Int).SetBytes(x2[:]), parity); ok {
			return p
		}
		n := new(big.Int).Add(new(big.Int).SetBytes(x[:]), big1)
		copy(x[:], leftPad(n.Bytes(), 32))
	}
}

// Validator is sha256(salt || sha256("user:pass")).
func Validator(user, pass string, salt []byte) []byte {
	inner := sha256.Sum256([]byte(user + ":" + pass))
	return sha256Concat(salt, inner[:])
}

// Confirmation is the proof the device checks. Only someone who knows the
// password can produce it, and it doubles as the shared-secret derivation.
func Confirmation(user, pass string, salt, clientPriv, clientPub, serverPub []byte, serverParity int) ([]byte, error) {
	v := Validator(user, pass, salt)
	vPubX, _ := PublicKey(v)
	vPoint := redp1(vPubX, 1)

	sPoint, ok := liftX(new(big.Int).SetBytes(serverPub), serverParity)
	if !ok {
		return nil, fmt.Errorf("server public key is not a point on the curve")
	}
	sPoint = addPoints(sPoint, vPoint)

	h := sha256Concat(clientPub, serverPub)

	vh := new(big.Int).Mul(new(big.Int).SetBytes(v), new(big.Int).SetBytes(h))
	vh.Add(vh, new(big.Int).SetBytes(clientPriv))
	vh.Mod(vh, curveR)

	z, _ := toMontgomery(scalarMult(vh, sPoint))
	return sha256Concat(h, z), nil
}

// NewPrivateKey returns 32 random bytes.
func NewPrivateKey() ([]byte, error) {
	b := make([]byte, 32)
	_, err := rand.Read(b)
	return b, err
}

func sha256Concat(parts ...[]byte) []byte {
	h := sha256.New()
	for _, p := range parts {
		h.Write(p)
	}
	return h.Sum(nil)
}

func leftPad(b []byte, n int) []byte {
	if len(b) >= n {
		return b[len(b)-n:]
	}
	out := make([]byte, n)
	copy(out[n-len(b):], b)
	return out
}
